### PR TITLE
Use ngx_small_light v0.6.5

### PR DESCRIPTION
**Pull request by dtan4**
## WHY
[ngx_small_light v0.6.5](https://github.com/cubicdaiya/ngx_small_light/releases/tag/v0.6.5) was released.
It includes memory-allocation optimization ([ChangeLog](https://github.com/cubicdaiya/ngx_small_light/blob/master/ChangeLog)).

### CODE REVIEW

**Comment by dtan4** [comment]
@spesnova Please review this! :bow:

**Comment by spesnova** [comment]
@dtan4 please pull `fix-wercker.yml` to fix CI
See https://github.com/wantedly/nginx-image-server/pull/27

**Comment by spesnova** [comment]
:+1:

**Comment by spesnova** [comment]
forgot to update README :sweat:

**Pull request merged**
