### PR TITLE
Introduce ngx_aws_auth module to convert private images

### PR DESCRIPTION
**Pull request by creasty**
## Why

Images uploaded with non-`public-read` ACL cannot be converted by smalllight due to an insufficient privilege, as it doesn't understand signature params `X-Amz-*`.
## What

https://chocoby.jp/blog/2016/01/31/ngx-small-light-s3-private-image/

### CODE REVIEW

**Comment by creasty** [comment]
No specs for actual s3 assets, huh?

**Comment by dtan4** [comment]
I'm afraid that ngx_aws_auth 1.1.1 is obsolete because it does not support [AWS Signature Version 4](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html).

How about using https://github.com/anomalizer/ngx_aws_auth/commit/9ea52e6d3f58dd2e68ccf9bc59b8cb8fee007fd4, the current master ?

**Comment by creasty** [comment]
> I'm afraid that ngx_aws_auth 1.1.1 is obsolete because it does not support AWS Signature Version 4.

Ha!

> How about using anomalizer/ngx_aws_auth@9ea52e6, the current master ?

Can we use the commit sha1 in an archive url just like a tag here?

**Comment by creasty** [comment]
> Can we use the commit sha1 in an archive url just like a tag here?

Seems like we can.

**Comment by dtan4** [comment]
Unfortunally CI failed with the error below. Please check again.

```
/bin/sh: 1: --add-module=/tmp/ngx_aws_auth-9ea52e6d3f58dd2e68ccf9bc59b8cb8fee007fd4: not found
```

**Comment by creasty** [comment]
> Unfortunally CI failed with the error below. Please check again.

Wut? That can't be.

**Comment by creasty** [comment]
Ouch...

**Pull request closed without merging**
