### PR TITLE
Validate resize parameter

### PR DESCRIPTION
**Pull request by dtan4**
## WHY
When we made request resizing image to VERY LARGE size to current nginx-image-server, it falls into busy and down. 

## WHAT
Validate resize parameters (`cw`, `dw`, `ch`, `dh`) at every request by Perl module.
It restricts them to __3072__ or under.

If oversize request is given, server will return `400 Bad Request`.

### CODE REVIEW

**Comment by luvtechno** [comment]
Curious about the threshold. How did you choose 3072?

Also, how much time does it take to invoke the perl process? Wanted to make sure overhead for each request is ignorable.

**Comment by dtan4** [comment]
Most of our request size is under 3000, so we decided threshold as 1024 * 3.

And I've tested performance of patched (= with validation) image server by locust. The result is below.

on Mac OS X, boot2docker

| user | hatch rate | rps |  failure(`%`) |
|--------|---------------|--------|---------------|
| 40 | 1 | 4.11 | 0% |

This result is nearly equal to current (= without validation) image server.
It seems that request overhead is ignorable.

**Comment by spesnova** [comment]
> Curious about the threshold. How did you choose 3072?

I tried many size (2000~150000) to find threshold yesterday.
Then I found over 18000 ~ 20000 causes nginx-image-server down (using AWS EC2 m3.large SSD).
And @awakia decided the detail. 

> Also, how much time does it take to invoke the perl process? Wanted to make sure overhead for each request is ignorable.

I'll check this later with [locust](http://locust.io/). Please see [performance test section](https://github.com/wantedly/nginx-image-server#performance-test) for how do we test.

**Comment by luvtechno** [comment]
Thanks guys.

> Most of our request size is under 3000

Is this based on production requests? If not, you may want to double check our iOS app folks. I was under impression our iPad app loads larger images...

**Comment by luvtechno** [comment]
BTW, I'm okay with deploying this change before verifying my points. I know the image server has been failing because of this issue. 

I'd rather prefer showing *some* of images over showing *no* images at all...

**Comment by spesnova** [comment]
1 container on m3.large

with validation

| user | hatch rate | rps | failure | total req |
|-------|---------------|------|----------|------------|
| 40  | 1                | 4.1 | 0.0       | 300       |
| 30  | 1                | 3.3 | 0.0       | 204       |
| 20 | 1                 | 2.4 | 0.0       | 254       |

CPU100% at 30user

current

| user | hatch rate | rps | failure | total req |
|-------|---------------|------|----------|------------|
| 40  | 1                | 4.5 | 0.0       | 247       |
| 30  | 1                | 3.1 | 0.0       | 288       |
| 20 | 1                 | 2.1 | 0.0       | 326	 |

CPU 100% at 30user

I checked with eyes too. LG

**Pull request merged**
